/*
2. Revenue by Category 
Calculate total revenue generated by each product category. 
Challenge: Include the percentage contribution of each category to total revenue.

*/

WITH category_revenue AS(	
	SELECT c.category_id, ROUND(SUM(oi.quantity*oi.price_per_unit),2) AS revenue
	FROM order_items oi
	LEFT JOIN products p ON oi.product_id=p.product_id
	LEFT JOIN category c ON p.category_id=c.category_id
	GROUP BY c.category_id)
SELECT category_id,revenue, ROUND(((revenue/(SELECT SUM(oi.quantity*oi.price_per_unit) FROM order_items oi
										LEFT JOIN products p ON oi.product_id=p.product_id
										LEFT JOIN category c ON p.category_id=c.category_id	))*100),2) AS percentage_contribution
FROM category_revenue
GROUP BY category_id,revenue
ORDER BY category_id
